// Package apispec Code generated by swaggo/swag. DO NOT EDIT
package apispec

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "VuGiang",
            "email": "tvugiang@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check the health status of the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "Check system health",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request ID (UUID)",
                        "name": "X-Request-Id",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Return data",
                        "schema": {
                            "$ref": "#/definitions/httpserver.APIResponse-service_CheckHealthResponse"
                        }
                    },
                    "400": {
                        "description": "Error object",
                        "schema": {
                            "$ref": "#/definitions/echo.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "echo.HTTPError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "httpserver.APIResponse-service_CheckHealthResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/service.CheckHealthResponse"
                },
                "pagination": {
                    "$ref": "#/definitions/httpserver.Pagination"
                },
                "requestId": {
                    "type": "string",
                    "example": "3bf74527-8097-4217-8485-ffe05d16f82e"
                }
            }
        },
        "httpserver.Pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "pageSize": {
                    "type": "integer",
                    "example": 10
                },
                "totalCount": {
                    "type": "integer",
                    "example": 42
                },
                "totalPages": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "service.CheckHealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Gaian User API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
