name: Prod Build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/go_starter_kit

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Check go.mod/go.sum are tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Build
        run: go build ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
          install-mode: goinstall
          only-new-issues: true

  prod-build:
    needs: lint
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Git tag
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          echo "IMAGE_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Build and Push Prod image
        run: |
          IMAGE_URI=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

      - name: Checkout deployment repo
        uses: actions/checkout@v4
        with:
          repository: giangtv270304/operations-starter-kit
          token: ${{ secrets.DEPLOYMENT_REPO_PAT }}
          path: operations-starter-kit

      - name: Commit and push changes
        working-directory: operations-starter-kit
        run: |
          FILE=inventory/group_vars/production/vars.yml
          sed -i "s/^image_tag: .*/image_tag: \"${{ env.IMAGE_TAG }}\"/" "$FILE"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "$FILE"
          git commit -m "ci: bump production image_tag to ${{ env.IMAGE_TAG }}" || echo "Nothing to change"
          git push
